In [6]:
students_data = {
    'student_id': [101, 102, 103, 104, 105, 106, 107],
    'name': ['Alice', 'Bob', None, 'David', 'Emma', 'Frank', 'Grace'],
    'email': ['alice@email.com', 'bob@email.com', 'charlie@email.com', None, 'emma@email.com', 'frank@email.com', 'grace@email.com'],
    'city': ['Mumbai', 'Delhi', 'Bangalore', 'Mumbai', None, 'Chennai', 'Delhi']
}
enrollments_data = {
    'student_id': [101, 102, 103, 105, 108, 109],
    'course_name': ['Python', 'Data Science', 'Python', 'Machine Learning', 'AI', 'Python'],
    'enrollment_date': ['2024-01-15', '2024-01-20', '2024-02-01', '2024-02-10', '2024-02-15', '2024-03-01']
}
scores_data = {
    'student_id': [101, 102, 104, 105, 106],
    'exam_score': [85, 92, 78, 88, 95]
}


In [7]:
import pandas as pd

student_df = pd.DataFrame(students_data)
enroll_df = pd.DataFrame(enrollments_data)
score_df = pd.DataFrame(scores_data)



In [34]:
# Display null value count and percentage for each column
# Fill missing 'city' values with 'Unknown'
# Drop rows where 'name' is missing
print("=== TASK 1: Data Preparation ===")

print(f"Original Students DataFrame:")
print(student_df)

nullCount = student_df.isnull().sum()
nullPercent = nullCount / len(student_df) *100

print(f"Null Value Analysis: \n")
for col in student_df.columns:
  print(f"Column: {col}, Nulls: {nullCount[col]} ({nullPercent[col]:.2f})")

student_df.fillna({'city':'Unknown'}, inplace=True)
len_before_drop = len(student_df)
student_df.dropna(subset=['name'],inplace=True)
len_after_drop = len(student_df)
print("Cleaned Students DataFrame: ",{len_after_drop})
print(student_df)

=== TASK 1: Data Preparation ===
Original Students DataFrame:
   student_id   name              email       city
0         101  Alice    alice@email.com     Mumbai
1         102    Bob      bob@email.com      Delhi
2         103   None  charlie@email.com  Bangalore
3         104  David               None     Mumbai
4         105   Emma     emma@email.com       None
5         106  Frank    frank@email.com    Chennai
6         107  Grace    grace@email.com      Delhi
Null Value Analysis: 

Column: student_id, Nulls: 0 (0.00)
Column: name, Nulls: 1 (14.29)
Column: email, Nulls: 1 (14.29)
Column: city, Nulls: 1 (14.29)
Cleaned Students DataFrame:  {6}
   student_id   name            email     city
0         101  Alice  alice@email.com   Mumbai
1         102    Bob    bob@email.com    Delhi
3         104  David             None   Mumbai
4         105   Emma   emma@email.com  Unknown
5         106  Frank  frank@email.com  Chennai
6         107  Grace  grace@email.com    Delhi


TASK-2 MULTIPLE JOIN OPERATION

In [35]:
#Inner Join

result = pd.merge(student_df,enroll_df, on='student_id',how='inner')
print(f"\nInner Join Result: ({len(result)} rows)")
print(result)


   student_id   name            email     city       course_name  \
0         101  Alice  alice@email.com   Mumbai            Python   
1         102    Bob    bob@email.com    Delhi      Data Science   
2         105   Emma   emma@email.com  Unknown  Machine Learning   

  enrollment_date  
0      2024-01-15  
1      2024-01-20  
2      2024-02-10  

Total record count 3


Total of 4 records are fetch as a result.
Inner join fetch the record from the both the table which has common id in it.
Student_id (104, 106, 107) is excluded because these id doesn't have matching data in the enrollment table

In [39]:
#Left Join

result = pd.merge(student_df,enroll_df, on='student_id',how='left')
print(f"\nLeft join result: ({len(result)} rows)")
print(result)



Left join result: (6 rows)
   student_id   name            email     city       course_name  \
0         101  Alice  alice@email.com   Mumbai            Python   
1         102    Bob    bob@email.com    Delhi      Data Science   
2         104  David             None   Mumbai               NaN   
3         105   Emma   emma@email.com  Unknown  Machine Learning   
4         106  Frank  frank@email.com  Chennai               NaN   
5         107  Grace  grace@email.com    Delhi               NaN   

  enrollment_date  
0      2024-01-15  
1      2024-01-20  
2             NaN  
3      2024-02-10  
4             NaN  
5             NaN  


total 6 rows are present
students 104,106,107 has NaN, because these doesn't have matching student_id in the course table (with respective to Student table)

In [40]:
#Right Join

result = pd.merge(student_df,enroll_df, on='student_id',how='right')
print(f"\nRight join result: ({len(result)} rows)")

print(result)


Right join result: (6 rows)
   student_id   name            email     city       course_name  \
0         101  Alice  alice@email.com   Mumbai            Python   
1         102    Bob    bob@email.com    Delhi      Data Science   
2         103    NaN              NaN      NaN            Python   
3         105   Emma   emma@email.com  Unknown  Machine Learning   
4         108    NaN              NaN      NaN                AI   
5         109    NaN              NaN      NaN            Python   

  enrollment_date  
0      2024-01-15  
1      2024-01-20  
2      2024-02-01  
3      2024-02-10  
4      2024-02-15  
5      2024-03-01  


Student_id : 103, 108, 109 doesnt gave name in the student table. These data are not present in the enrollment table

In [45]:
result = pd.merge(student_df,enroll_df, on='student_id',how='outer',indicator=True)
print(f"\nOuter join result: ({len(result)} rows)")

print(result)
missing_row = result['name'].isnull() | result['course_name'].isnull()
print(result[missing_row])


Outer join result: (9 rows)
   student_id   name            email     city       course_name  \
0         101  Alice  alice@email.com   Mumbai            Python   
1         102    Bob    bob@email.com    Delhi      Data Science   
2         103    NaN              NaN      NaN            Python   
3         104  David             None   Mumbai               NaN   
4         105   Emma   emma@email.com  Unknown  Machine Learning   
5         106  Frank  frank@email.com  Chennai               NaN   
6         107  Grace  grace@email.com    Delhi               NaN   
7         108    NaN              NaN      NaN                AI   
8         109    NaN              NaN      NaN            Python   

  enrollment_date      _merge  
0      2024-01-15        both  
1      2024-01-20        both  
2      2024-02-01  right_only  
3             NaN   left_only  
4      2024-02-10        both  
5             NaN   left_only  
6             NaN   left_only  
7      2024-02-15  right_only  
8 

Task 3: Lookup Operation and Automation

In [8]:
scores = dict(zip(scores_data['student_id'],scores_data['exam_score']))
student_data = student_df.copy()
student_data['exam_score'] = student_data['student_id'].map(scores)

print(student_data)

   student_id   name              email       city  exam_score
0         101  Alice    alice@email.com     Mumbai        85.0
1         102    Bob      bob@email.com      Delhi        92.0
2         103   None  charlie@email.com  Bangalore         NaN
3         104  David               None     Mumbai        78.0
4         105   Emma     emma@email.com       None        88.0
5         106  Frank    frank@email.com    Chennai        95.0
6         107  Grace    grace@email.com      Delhi         NaN


In [9]:
student_record = pd.merge(student_df,score_df,on='student_id',how='left')

print(student_record)

   student_id   name              email       city  exam_score
0         101  Alice    alice@email.com     Mumbai        85.0
1         102    Bob      bob@email.com      Delhi        92.0
2         103   None  charlie@email.com  Bangalore         NaN
3         104  David               None     Mumbai        78.0
4         105   Emma     emma@email.com       None        88.0
5         106  Frank    frank@email.com    Chennai        95.0
6         107  Grace    grace@email.com      Delhi         NaN


In [13]:
%timeit  pd.merge(student_df,score_df,on='student_id',how='left')

%timeit  student_data['student_id'].map(scores)

1.18 ms ± 152 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
263 µs ± 40.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Since we are add one column .map() is more efficient that merge.
Merge can be used when more than 2 columns need to be added. By using merge, this will create a new dataframe. causing more time and memory when compared to map()

SIMPLE AUTOMATION

In [18]:
def auto_merge(df1, df2, join_type, key_column):
  print(pd.merge(df1,df2,on=key_column,how=join_type))
  print("\n")


auto_merge(student_df,score_df,'outer','student_id')
auto_merge(student_df,score_df,'right','student_id')


   student_id   name              email       city  exam_score
0         101  Alice    alice@email.com     Mumbai        85.0
1         102    Bob      bob@email.com      Delhi        92.0
2         103   None  charlie@email.com  Bangalore         NaN
3         104  David               None     Mumbai        78.0
4         105   Emma     emma@email.com       None        88.0
5         106  Frank    frank@email.com    Chennai        95.0
6         107  Grace    grace@email.com      Delhi         NaN


   student_id   name            email     city  exam_score
0         101  Alice  alice@email.com   Mumbai          85
1         102    Bob    bob@email.com    Delhi          92
2         104  David             None   Mumbai          78
3         105   Emma   emma@email.com     None          88
4         106  Frank  frank@email.com  Chennai          95


