# -*- coding: utf-8 -*-
"""Data Prep & Feature Engineering .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XZkmadZSN_Ac8pAyGgwX9hAUz5cU_Nle
"""

import pandas as pd

data = {
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Female'],
    'City': ['Mumbai', 'Delhi', 'Chennai', 'Mumbai', 'Delhi'],
    'Size': ['Small', 'Large', 'Medium', 'Large', 'Small'],
    'Age': [25, 45, 32, 60, 28],
    'Fare': [15, 300, 85, 450, 20]
}

df = pd.DataFrame(data)

from sklearn.preprocessing import LabelEncoder

#Label encoding for the gender
gender_encoder = LabelEncoder()
df["Gender"] = gender_encoder.fit_transform(df["Gender"])
#male -> 1 and female -0 (vice-versa)

#One-hot encoding for the city .Drop one column
df = pd.get_dummies(df, columns=["City"],drop_first=True)

#for size : ordered Label encoding
size_mapping = {
    'Small': 0,
    'Medium': 1,
    'Large': 2
}

df['Size'] = df['Size'].map(size_mapping)

print("After Encoding:\n", df)

from sklearn.preprocessing import RobustScaler

#Feature based scaling
scaler = RobustScaler()
df[['Age', 'Fare']] = scaler.fit_transform(df[['Age', 'Fare']])

print("\nAfter Scaling:\n", df)

"""Fare column contains an outlier value (450) which can distort scaling methods that relyon the mean and std deviation. Robust scaler is better choice than standard sclar/minmax scaler because it uses the median and IQR and making it more resistant to the extreme value"""