# -*- coding: utf-8 -*-
"""ml-leakage-pipeline-Indhu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBeMJ8WpFLjKi3WJ4W-xR_gbThMTyK0B
"""

import numpy as np
import pandas as pd

data_size = 150

#area_sqft, num_bedrooms, age_years, and a target column price_lakhs

area_sqft = np.random.randint(500, 3000, data_size)
num_bedrooms = np.random.randint(2, 7, data_size)
age_years = np.random.randint(3, 15,data_size)

price_lakhs = (
    area_sqft * 0.05 +
    num_bedrooms * 5 -
    age_years * 0.3 +
    np.random.normal(0, 5, data_size)
)

data = pd.DataFrame({
    'area_sqft': area_sqft,
    'num_bedrooms': num_bedrooms,
    'age_years': age_years,
    'price_lakhs': price_lakhs
})

print(data)

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


X = data[['area_sqft', 'num_bedrooms', 'age_years']]
y = data['price_lakhs']

# Step 5: Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 6: Build and train model
model = LinearRegression()
model.fit(X_train, y_train)

# Step 7: Print intercept and coefficients
print("\nIntercept:", model.intercept_)

coefficients = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model.coef_
})

print("\nFeature Coefficients:")
print(coefficients)

# Step 8: Predictions
y_pred = model.predict(X_test)

# Step 9: Display first five actual vs predicted
comparison = pd.DataFrame({
    'Actual Price': y_test.values[:5],
    'Predicted Price': y_pred[:5]
})

print("\nFirst 5 Actual vs Predicted Values:")
print(comparison)

"""TASK 2"""

# Import evaluation metrics
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Calculate metrics
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("Model Evaluation Metrics:")
print("MAE :", mae)
print("RMSE:", rmse)
print("R²  :", r2)

# MAE  -> Average absolute error between actual and predicted prices.
# RMSE -> Penalizes large errors more heavily than MAE.
# R²   -> Shows how much variance in price is explained by the model (closer to 1 is better).

import matplotlib.pyplot as plt

# Compute residuals
residuals = y_test - y_pred

# Plot histogram
plt.figure()
plt.hist(residuals, bins=15)
plt.title("Histogram of Residuals")
plt.xlabel("Residual Value")
plt.ylabel("Frequency")
plt.show()

# A residual = Actual value - Predicted value.
# If histogram is roughly symmetric and centered around 0,
# it suggests the model errors are random and unbiased.
#

